name: radarr
description: Facilitate the communication to and from Radarr's API, a movie
  collection manager for Usenet and BitTorrent users.
version: 2.1.2
homepage: https://github.com/CometTools/LunaSea/tree/master/packages/radarr
repository: https://github.com/CometTools/LunaSea/tree/master/packages
issue_tracker: https://github.com/CometTools/LunaSea/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  test: ^1.26.2

scripts:
  build: pub run build_runner build --delete-conflicting-outputs
